### PR TITLE
Migrated to using SKY UX from NPM instead of Bower

### PR DESCRIPTION
**Pull request by Blackbaud-BobbyEarl**

### CODE REVIEW

**Comment by Blackbaud-JoePrice** [comment]
After applying this patch, I get the following error when running `grunt buildcustom`:

```
Running "sass:app" (sass) task
>> Error: File to import not found or unreadable: ../node_modules/@blackbaud/skyux-design-tokens/scss/variables.scss.
>>         on line 1 of node_modules/blackbaud-skyux/scss/_variables.scss
>>         from line 1 of node_modules/blackbaud-skyux/scss/_mixins.scss
>>         from line 7 of src/scss/app.scss
>> >> @import '../node_modules/@blackbaud/skyux-design-tokens/scss/variables.scss'
>>    ^
Warning:  Use --force to continue.
```

To me, this looks like an issue with https://github.com/blackbaud/skyux/blob/master/scss/_variables.scss#L1 (rather than this patch). The path back to node_modules that works for me is `@import '../../../node_modules/@blackbaud/skyux-design-tokens/scss/variables.scss';`

**Comment by Blackbaud-BobbyEarl** [comment]
Good catch @Blackbaud-JoePrice.  Unfortunately this is due to a problem downstream.  Consider this PR on hold until I can resolve the issue.

Thanks!

**Comment by Blackbaud-JoePrice** [comment]
One other thing I noticed is that this code has the skyux asset versions hardcoded -- https://github.com/blackbaud/Blackbaud-CRM-SKY/blob/master/Blackbaud.AppFx.MajorGiving.Mobile.Sky/src/dependencies.js. Not totally related to the bower to npm switch, but it is worth noting.

**Comment by Blackbaud-JoePrice** [comment]
@Blackbaud-BobbyEarl Thanks, Bobby! This is working great. 

However, I think this example code may not be ready to update the CDN urls just yet since that requires Angular 1.6.x readiness. When I built with 1.23.3 CDN dependencies, I get a number of console errors in the rendered application.

```
Error: [$injector:modulerr] Failed to instantiate module frog due to:
[$injector:nomod] Module 'frog' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.6.5/$injector/nomod?p0=frog
d/<@https://sky.blackbaudcdn.net/skyux/1.23.3/js/sky-bundle.min.js:12:30907
wa/</</<@https://sky.blackbaudcdn.net/skyux/1.23.3/js/sky-bundle.min.js:13:10080
b@https://sky.blackbaudcdn.net/skyux/1.23.3/js/sky-bundle.min.js:13:9537
wa/</<@https://sky.blackbaudcdn.net/skyux/1.23.3/js/sky-bundle.min.js:13:9854
m/<@https://sky.blackbaudcdn.net/skyux/1.23.3/js/sky-bundle.min.js:13:19765
f@https://sky.blackbaudcdn.net/skyux/1.23.3/js/sky-bundle.min.js:12:31339
m@https://sky.blackbaudcdn.net/skyux/1.23.3/js/sky-bundle.min.js:13:19613
mb@https://sky.blackbaudcdn.net/skyux/1.23.3/js/sky-bundle.min.js:13:21628
g@https://sky.blackbaudcdn.net/skyux/1.23.3/js/sky-bundle.min.js:13:7454
ka@https://sky.blackbaudcdn.net/skyux/1.23.3/js/sky-bundle.min.js:13:7764
ja@https://sky.blackbaudcdn.net/skyux/1.23.3/js/sky-bundle.min.js:13:7002
@https://sky.blackbaudcdn.net/skyux/1.23.3/js/sky-bundle.min.js:18:14596
j@https://sky.blackbaudcdn.net/skyux/1.23.3/js/sky-bundle.min.js:2:7942
fireWith@https://sky.blackbaudcdn.net/skyux/1.23.3/js/sky-bundle.min.js:2:8710
ready@https://sky.blackbaudcdn.net/skyux/1.23.3/js/sky-bundle.min.js:2:10527

http://errors.angularjs.org/1.6.5/$injector/modulerr?p0=frog…net%2Fskyux%2F1.23.3%2Fjs%2Fsky-bundle.min.js%3A2%3A10527%0A
```

**Comment by Blackbaud-BobbyEarl** [comment]
Makes sense @Blackbaud-JoePrice.  I'll revert those changes in this PR and keep this just for migrating to npm from bower for SKY UX.

**Pull request closed without merging**
